CREATE TABLE IF NOT EXISTS goods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  location VARCHAR(256) NOT NULL DEFAULT '默认货架',
  status VARCHAR(32) NOT NULL DEFAULT 'stored',
  stored_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  taken_at DATETIME NULL,
  operator VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
