name: CMake Build

on:
  push:
    branches:
      - master
      - main

  pull_request:

jobs:

  build:

    strategy:
      fail-fast: false

      matrix:

        include:

          - os: ubuntu-latest
            compiler: gcc
            cc: gcc
            cxx: g++

          - os: ubuntu-latest
            compiler: clang
            cc: clang
            cxx: clang++

          - os: windows-latest
            compiler: msvc

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

###########################################################
# Linux
###########################################################

      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            default-libmysqlclient-dev \
            pkg-config

      - name: Configure Linux
        if: runner.os == 'Linux'
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          cmake \
            -B build \
            -DCMAKE_BUILD_TYPE=Release

###########################################################
# Windows
###########################################################

      - name: Clone vcpkg
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install MySQL
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          .\vcpkg\vcpkg.exe install libmysql:x64-windows

      - name: Configure Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cmake `
            -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="$PWD\vcpkg\scripts\buildsystems\vcpkg.cmake"

###########################################################
# Build
###########################################################

      - name: Build
        run: cmake --build build --config Release

###########################################################
# Test
###########################################################

      - name: Test
        run: ctest --test-dir build --build-config Release
